services:
  db-postgres:
    image: postgres:13.21-alpine3.22
    env_file: .env
    container_name: postgres_container
    restart: always
    volumes:
      - pg-data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  pg-data:
