services:
  db-mariadb:
    image: mariadb:lts
    env_file: .env
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-mariadb-data:/var/lib/mysql
    networks:
      - wordpress-network
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - wordpress-network
    environment:
      PMA_HOST: db-mariadb:3306
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      db-mariadb:
        condition: service_healthy

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./src/wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network
    environment:
      - WORDPRESS_DB_HOST=db-mariadb:3306
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db-mariadb:
        condition: service_healthy

  webservice:
    image: nginx:stable-alpine-perl
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress-network
    depends_on:
      - wordpress
    # healthcheck:
    #   test: curl --fail http://localhost/ || exit 1
    #   interval: 40s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 60s

volumes:
  wordpress:
  db-mariadb-data:

networks:
  wordpress-network:
    driver: bridge
