services:
  mariadb:
    image: mariadb:lts
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_PASSWORD}
      - MARIADB_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=${DATABASE_USER}

    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
