services:
  database:
    container_name: ${PROJECT_NAME}-database
    image: mariadb:lts
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_bedrock_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  php:
    container_name: ${PROJECT_NAME}-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    restart: unless-stopped
    volumes:
      - ./${PROJECT_NAME}:/var/www/html
    networks:
      - wp_bedrock_network
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "php-fpm", "--test"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./${PROJECT_NAME}:/var/www/html
      - ./docker/nginx/wp_bedrock.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp_bedrock_network
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
    driver: local

networks:
  wp_bedrock_network:
    driver: bridge
