services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./sql/${ENVIROMENT}:/docker-entrypoint-initdb.d
    ports:
      - "${PORTA}:3306"
    restart: always
