services:
  db-mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    ports:
      - "${PORTA}:3306"
    volumes:
      - ../Scripts/${ENVIROMENT}:/docker-entrypoint-initdb.d
      - db-mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

volumes:
  db-mariadb-data:
