services:
  db-sqlserver:
    #image: mcr.microsoft.com/azure-sql-edge:1.0.4
    image: mcr.microsoft.com/mssql/server
    env_file:
      - .env
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - db-sqlserver-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1",
        ]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  db-sqlserver-data:
